name: Deploy

on:
    push:
        branches:
            - main # Set a branch to deploy when pushed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install
              run: npm install
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PWD }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: vmatekole/slachub:latest
